"""The pre-trade risk gate.

Every Signal generated by a Strategy is evaluated by `evaluate()` before any order
is submitted. The gate is pure: takes inputs, returns a decision. No side effects.
The caller writes the decision to the audit log and (if approved) submits the order.

This is the most safety-critical code in the system. Treat it accordingly:
  - Every branch should have a unit test.
  - First failure short-circuits — no fancy aggregation.
  - When in doubt, reject. A false-negative costs an opportunity; a false-positive
    costs real money.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import time
from decimal import Decimal

from trident.risk.limits import RiskLimits, daily_loss_tripped
from trident.risk.sizing import position_fits_buying_power, position_notional, position_size
from trident.strategies.base import Signal


@dataclass(frozen=True)
class AccountState:
    equity: Decimal
    starting_equity_today: Decimal
    buying_power: Decimal
    open_positions: dict[str, int] = field(default_factory=dict)  # symbol -> qty


@dataclass(frozen=True)
class MarketState:
    bid: Decimal | None = None
    ask: Decimal | None = None
    avg_daily_volume: int | None = None
    kill_switch_active: bool = False


@dataclass(frozen=True)
class GateDecision:
    approved: bool
    reason: str
    detail: str
    shares: int = 0


def _reject(reason: str, detail: str) -> GateDecision:
    return GateDecision(approved=False, reason=reason, detail=detail, shares=0)


def evaluate(
    signal: Signal,
    account: AccountState,
    market: MarketState,
    limits: RiskLimits,
    et_now: time,
) -> GateDecision:
    if market.kill_switch_active:
        return _reject("kill_switch", "Kill switch engaged; no new entries.")

    if et_now < limits.no_entry_before:
        return _reject(
            "too_early",
            f"Entry attempted at {et_now} but no entries before {limits.no_entry_before}.",
        )
    if et_now >= limits.no_entry_after:
        return _reject(
            "too_late",
            f"Entry attempted at {et_now} but no entries at/after {limits.no_entry_after}.",
        )

    if signal.side not in {"long", "short"}:
        return _reject("bad_side", f"Unknown side: {signal.side!r}")

    if signal.symbol in account.open_positions:
        return _reject("existing_position", f"Already have a position in {signal.symbol}.")
    if len(account.open_positions) >= limits.max_concurrent_positions:
        return _reject(
            "max_positions",
            f"At max concurrent positions ({limits.max_concurrent_positions}).",
        )

    if daily_loss_tripped(
        account.starting_equity_today, account.equity, limits.daily_loss_limit_pct
    ):
        return _reject(
            "daily_loss_limit",
            f"Daily loss limit of {limits.daily_loss_limit_pct}% reached.",
        )

    if signal.side == "long":
        if signal.stop_price >= signal.entry_price:
            return _reject(
                "bad_stop",
                f"Long signal stop {signal.stop_price} not below entry {signal.entry_price}.",
            )
        if signal.target_price <= signal.entry_price:
            return _reject(
                "bad_target",
                f"Long signal target {signal.target_price} not above entry {signal.entry_price}.",
            )
    else:  # short
        if signal.stop_price <= signal.entry_price:
            return _reject("bad_stop", "Short signal stop must be above entry.")
        if signal.target_price >= signal.entry_price:
            return _reject("bad_target", "Short signal target must be below entry.")

    if market.bid is not None and market.ask is not None and market.bid > 0 and market.ask > 0:
        mid = (market.bid + market.ask) / Decimal("2")
        spread_pct = (market.ask - market.bid) / mid * Decimal("100")
        if spread_pct > limits.max_spread_pct:
            return _reject(
                "wide_spread",
                f"Spread {spread_pct:.3f}% exceeds limit {limits.max_spread_pct}%.",
            )

    if (
        market.avg_daily_volume is not None
        and market.avg_daily_volume < limits.min_avg_daily_volume
    ):
        return _reject(
            "low_volume",
            f"Avg daily volume {market.avg_daily_volume} < min {limits.min_avg_daily_volume}.",
        )

    shares = position_size(
        account_equity=account.equity,
        risk_per_trade_pct=limits.risk_per_trade_pct,
        entry_price=signal.entry_price,
        stop_price=signal.stop_price,
    )
    if shares <= 0:
        return _reject("zero_shares", "Position sizing returned zero shares.")

    if not position_fits_buying_power(shares, signal.entry_price, account.buying_power):
        return _reject(
            "insufficient_buying_power",
            f"Need ~{shares * signal.entry_price:.2f}; have {account.buying_power}.",
        )

    notional = position_notional(shares, signal.entry_price)
    max_notional = account.equity * (limits.max_position_notional_pct / Decimal("100"))
    if notional > max_notional:
        return _reject(
            "position_too_large",
            f"Notional {notional:.2f} exceeds cap {max_notional:.2f}.",
        )

    return GateDecision(
        approved=True,
        reason="ok",
        detail=f"Approved {shares} shares of {signal.symbol} @ {signal.entry_price}.",
        shares=shares,
    )
